name: filterinio
description: A starting point for Dart libraries or applications.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.4.3

# Add regular dependencies here.
dependencies:
  equatable: ^2.0.5
  freezed_annotation: ^2.4.3
  json_annotation: ^4.9.0
  mink_dart_utils:
    git:
      url: git@github.com:MinkTec/mink_utils.git
      ref: HEAD
      path: packages/mink_dart_utils

dev_dependencies:
  build_runner: ^2.4.7
  freezed: ^2.5.6
  json_serializable: ^6.7.1
  lints: ^3.0.0
  test: ^1.24.0
